services:
  # run jupyter notebook inside jupyter 
  jupyter-notebook:
    image:  piloxita/dsci522-dockerfile-practice
    ports:
      - "1616:8888"
    volumes:
      - .:/home/jovyan
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/amd64