# environment.yml
name: my-env
channels:
    - conda-forge
    - defaults
dependencies:
    - pandas=2.2.2
    - pandera=0.20.4
    - python=3.11
    - scipy=1.10.1
    - matplotlib=3.9.2
    - scikit-learn=1.2.2
    - pip
    - pip:
      - deepchecks==0.18.1